### ISSUE TITLE
Collabora : 502 Bad Gateway

### ISSUE THREAD

**Issue by ybabel** [crazy-max/docker-nextcloud#10]
Hello,
I launched you docker-compose.yml on my server. Nextcloud works fine, but, I can't get collabora to work.

I set `https://office.mydomain.fr` in nextcloud `https://cloud.mydomain.fr/settings/admin/richdocuments'`.

I got `GuzzleHttp\Exception\ServerException: Server error: 'GET https://office.mydomain.fr/hosting/discovery' resulted in a `502 Bad Gateway` response: Bad Gateway `

same with http:// . If I add port 9980 it's not responding (Connection refused)

My docker-compose.yml is exactly the same as your's except for domains. (nextcloud is working fine)

**Comment by crazy-max** [comment]
Hello @ybabel,

I was able to make it work but without SSL unfortunately, check the latest docker-compose I have pushed :

![image](https://user-images.githubusercontent.com/1951866/51766836-d978a580-20db-11e9-8e3a-2d0d9dcab4f0.png)

But there is an error with the Nextcloud Collabora plugin when I want to open a document :

```
nextcloud_1  | 2019/01/25 19:51:58 [error] 62#62: *430 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot declare class GuzzleHttp\Handler\CurlFactory, because the name is already in use in /var/www/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 15" while reading response header from upstream, client: 172.18.0.4, server: , request: "GET /apps/richdocuments/index?fileId=166&requesttoken=uljMvHO7XWrO6Jix%2BdmmR%2BTLIxCJOavcK4IlJEDboeM%3D%3A7gCf3x2OdjuChdvzsJLQL9OmSyfDdfuuT9sdRgmY1dc%3D HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm7.sock:", host: "nextcloud.docker"
```

I suggest to open an issue on [their repository](https://github.com/nextcloud/richdocuments/issues) for this.

Also don't forget to set the server URL in your Nextcloud configuration :

![image](https://user-images.githubusercontent.com/1951866/51766653-65d69880-20db-11e9-9932-6ba1d5031c06.png)

If you want to enable SSL, you have to use [Apache as a reverse proxy](https://nextcloud.com/collaboraonline/).

Feel free to open a PR if you have a working configuration with Apache.
