### ISSUE TITLE
occ memories:places-setup -> polygon not supported?

### ISSUE THREAD

**Issue by scubao** [crazy-max/docker-nextcloud#111]
Hi,

I've got a problem with the memories addin within your setup (which I like, working perfectly btw!)
[memories requires oc_ table prefix](https://github.com/pulsejet/memories/issues/427)

Looks like memories needs the oc_ prefix - can you give me any hint how to achieve this with your image?
I tried       - "NEXTCLOUD_TABLE_PREFIX=oc_" in the docker compose but this doesn't work unfortunately.

Kind regards

**Comment by penguinsam** [comment]
I ran into the same issue too, @scubao did you finally find a fix or workaround?

**Comment by crazy-max** [comment]
Hard to tell without any info of your setup. Please create a proper [bug report](https://github.com/crazy-max/docker-nextcloud/issues/new?assignees=&labels=&template=bug_report.md).

**Comment by scubao** [comment]
Hi, sorry for the late reply. I build my own package and changed it a) to the latest version and b) changed a file to have the prefix to oc_ 

I'm not a developer but happy to do a pull request with a variable if crazymax agrees and tell me how to do that properly.

Best
Oliver
