### ISSUE TITLE
Redis in config.php

### ISSUE THREAD

**Issue by MarcelFranken** [crazy-max/docker-nextcloud#13]
Hi there,

first of all thank you for your great and easy working docker image.
I will use it in my production environment.

I just have one question, what is the best way to enable redis in config.php after initial/first install?

Thank you

**Comment by crazy-max** [comment]
Hi @MarcelFranken, take at look at https://github.com/crazy-max/docker-nextcloud#redis-cache

**Comment by MarcelFranken** [comment]
Is it possible to do this automaticly?

**Comment by crazy-max** [comment]
No , it's an optional feature and it would be hard to maintain configuration across releases.
