### ISSUE TITLE
Exception: Updates between multiple major versions and downgrades are unsupported.

### ISSUE THREAD

**Issue by georgikoemdzhiev** [crazy-max/docker-nextcloud#132]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-nextcloud/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hello,

Today I decided to update to the latest version of the image after 2 years (yes, I know :D). After performing the following steps:

1. docker stop current_container_id
2. docker rm  current_container_id
3. docker pull crazymax/nextcloud:latest
4. docker run -d -p 8000:8000 --name nextcloud -v /home/manjaro/NextCloud:/data -e DB_PASSWORD=????? crazymax/nextcloud:latest

I was treated by this message:

```txt
Exception: Updates between multiple major versions and downgrades are unsupported.
Detailed logs:

-Preparing update
-Set log level to debug
-Turned on maintenance mode
-Exception: Updates between multiple major versions and downgrades are unsupported.

The update was unsuccessful. For more information [check our forum post](https://help.nextcloud.com/t/updates-between-multiple-major-versions-are-unsupported/7094) covering this issue.
```

I tried to delete all of the folders in `/home/manjaro/NextCloud` except `config` and `data` as it was suggested on the official Nextdrive forum and restarting the latest version of the container but that did not help.

What am I missing here, could you please provide some pointers? 

Thank you in advance!

### Expected behaviour

The version upgrade process finishes successfully.

### Actual behaviour

Getting an exception.

### Steps to reproduce

1. Miss couple of major versions
2. docker stop current_container_id
2. docker rm  current_container_id
3. docker pull crazymax/nextcloud:latest
4. docker run -d -p 8000:8000 --name nextcloud -v /home/manjaro/NextCloud:/data -e DB_PASSWORD=????? crazymax/nextcloud:latest

### Docker info

```text
[manjaro@manjaro ~]$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-tp-docker)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 36cc874494a56a253cd181a1a685b44b58a2e34a.m
 runc version: v1.0.1-0-g4144b638
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.50-2-MANJARO-ARM
 Operating System: Manjaro ARM
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.717GiB
 Name: manjaro
 ID: RU6V:WJZ5:4WPR:2VPI:PGQV:U4T2:FYVN:KTRX:WS53:WI27:36CT:4UEC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
```

### Logs

```text
N/A
```

**Comment by georgikoemdzhiev** [comment]
I am closing this ticket. After more research, I found that after deleting all of the folders in my docker volume (except `config` and `data`) I had to change the `version` do the version of the "latest" image (in my case 27.0.1)

**Comment by crazy-max** [comment]
Yes you need to update to the next major (26) and then 27 otherwise this error message is prompted.
