### ISSUE TITLE
Avatar generation does not work

### ISSUE THREAD

**Issue by MarcelFranken** [crazy-max/docker-nextcloud#14]
Hi again,

i have the same problem as discussed at https://github.com/linuxserver/docker-nextcloud/issues/81

Is there a fix available?

Greetings

**Comment by crazy-max** [comment]
Hi @MarcelFranken, seems to be an issue with PHP GD extension, it works for PHP 7.1 :

![image](https://user-images.githubusercontent.com/1951866/54496835-02573300-48f4-11e9-969c-c58042d1be97.png)

I keep you in touch

**Comment by crazy-max** [comment]
@MarcelFranken Ok it's an issue with php-gd. I will push an update.

**Comment by crazy-max** [comment]
@MarcelFranken Using edge repository does not work but it's working with 3.7 repo. Will wait for an upstream update of the current base alpine 3.9 image.

**Comment by crazy-max** [comment]
@MarcelFranken Fyi it works fine on 16.0.0RC1 :

![image](https://user-images.githubusercontent.com/1951866/55961587-82f91d00-5c6f-11e9-9b25-75fb2bdb5674.png)

**Comment by MarcelFranken** [comment]
16.0.0? Where can i find this?

**Comment by crazy-max** [comment]
@MarcelFranken It's a release candidate for the moment but I can publish a 16.0.0RC1 image if you want.

**Comment by MarcelFranken** [comment]
You dont have to, we can wait until they release a stable version.

**Comment by crazy-max** [comment]
@MarcelFranken Nextcloud 16.0.0 is now stable and released.
