### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by ThesiiNCey** [crazy-max/docker-nextcloud#154]
### Description

First i want to say Thank you its Balzing fast your Docker image :D

i want to ask can you add the missing things like imagemagick ( svg support )

**Comment by ThesiiNCey** [comment]
ah and fresh installed -> https://github.com/crazy-max/docker-nextcloud/tree/master/examples/compose all is working but i cant see logs window is complete grey

**Comment by crazy-max** [comment]
Yes we have this package installed: https://github.com/crazy-max/docker-nextcloud/blob/af4eb6e66cfb6720940c94de9388fc5481292d3f/Dockerfile-29#L28

And additional ones with latest stable: https://github.com/crazy-max/docker-nextcloud/pull/157#discussion_r1623228634

> First i want to say Thank you its Balzing fast your Docker image :D

:heart:
