### ISSUE TITLE
Reverse-Proxy-Header-Configuration error

### ISSUE THREAD

**Issue by MarcelFranken** [crazy-max/docker-nextcloud#16]
Hello,
after updating to NC 16 i get this message on my nextcloud instance:
The reverse proxy header configuration is incorrect, or you are accessing Nextcloud from a trusted proxy. If not, this is a security issue and can allow an attacker to spoof their IP address as visible to the Nextcloud. Further information can be found in the documentation.

Any ideas?

Best regards

**Comment by crazy-max** [comment]
Check `trusted_proxies` and `forwarded_for_headers` in your config.

**Comment by MarcelFranken** [comment]
Hi crazy-max, yeah i know about this. But i didnt found anything in your docker container.

**Comment by crazy-max** [comment]
> in your docker container.

Nothing to do with the container, it concerns the Nextcloud configuration I think. Can you display your configuration (without secret, crendentials) pls ?

**Comment by MarcelFranken** [comment]
ok, maybe you can add this to your documentation :-)
Here is the output of the command:
`{
    "system": {
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "tempdirectory": "\/data\/tmp",
        "supportedDatabases": [
            "sqlite",
            "mysql",
            "pgsql"
        ],
        "logtimezone": "Europe\/Berlin",
        "logdateformat": "Y-m-d H:i:s",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "apps_paths": [
            {
                "path": "\/var\/www\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/data\/userapps",
                "url": "\/userapps",
                "writable": true
            }
        ],
        "mail_smtpmode": "smtp",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.localhost"
        ],
        "dbtype": "mysql",
        "version": "16.0.0.9",
        "overwrite.cli.url": "http:\/\/cloud.localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "maintenance": false,
        "overwriteprotocol": "https",
        "updatechecker": false,
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        }
    }
}
`

**Comment by MarcelFranken** [comment]
i added the specific line into my config.php, now it works perfect.

**Comment by crazy-max** [comment]
@MarcelFranken Nice and thx a lot for your donation :heart:
