### ISSUE TITLE
Internal Server error

### ISSUE THREAD

**Issue by solisinvictum** [crazy-max/docker-nextcloud#163]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-nextcloud/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

1). git clone this repo
2) cd to the example/compose folder
3) sudo docker compose up
4) cli everything fine
5) open browser ip:8000

Result:

Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

### Expected behaviour

to work.

### Actual behaviour

trows internal error

### Steps to reproduce

see above

### Docker info

```text
latest
```

### Logs

```text
-
```

**Comment by crazy-max** [comment]
Please show "Docker info" and "Logs"

Closing in the meantime.
