### ISSUE TITLE
Help!! Why my nextcloud after success create admin and it will change from https to http?

### ISSUE THREAD

**Issue by EricYoong** [crazy-max/docker-nextcloud#19]
#### Steps to reproduce this issue

1. Success setup.
2. Create an admin from the nextcloud.
3. Redirect to main page of success login to nextcloud

#### Expected behaviour

> The url supposingly will continue as https

#### Actual behaviour

> The url from https will change back to http

### Configuration

* Docker version (type `docker --version`) : Docker version 18.09.2, build 6247962
* Docker compose version if applicable (type `docker-compose --version`) : docker-compose version 1.23.2, build 1110ad01
* Platform (Debian 9, Ubuntu 18.04, ...) : windows 
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker info

```
> Output of command `docker info`
```
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 44
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.768GiB
Name: linuxkit-00155d009001
ID: BKIK:ZFGK:Z7RQ:HIBA:3QSH:UITO:RAMB:XFST:MKN3:O23A:4GUE:KHOY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 81
 Goroutines: 98
 System Time: 2019-05-17T09:28:31.1989298Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

**Comment by crazy-max** [comment]
Hi, can you post your compose and .env files pls? (without sensitive data)

**Comment by crazy-max** [comment]
And logs

**Comment by EricYoong** [comment]
I figure it out by adding 'overwriteprotocol' => 'https' in the config.php in nextcloud

**Comment by EricYoong** [comment]
thank you max!!!
