### ISSUE TITLE
Problems when importing .ics file to Calendar app

### ISSUE THREAD

**Issue by seth100** [crazy-max/docker-nextcloud#2]
Hi,

I'm trying to import a `.ics` file in Calendar app and I have many failures after process.
It worked with default nextcloud docker image and same `docker-compose-yml` configuration.
I'm using your image because `cron` works very well for the News app.
While importing I see many `Strict-Transport-Security: The connection to the site is untrustworthy, so the specified header was ignored.` warning in debugging console.

Do you have any issue like that? Could you please try to import e.g. a `.ics` exported from Google Calendar?
Thanks

**Comment by crazy-max** [comment]
Hi @seth100 !
Ok i will try to import an ics, i'll keep u in touch

**Comment by seth100** [comment]
Thank you @crazy-max

**Comment by crazy-max** [comment]
I had no problem while importing a google calendar ics with my nextcloud image.
I have made the following tests :

* `docker run --rm -d -p 8000:80 --name nextcloud crazy-max/nextcloud:latest`
* Open browser to my docker-machine `http://192.168.99.100:8000`
* Create a nextcloud admin account
* Install calendar plugin
* Import Google Calendar ics

Where do you see those warnings ? In your browser console or nextcloud logs ?

**Comment by seth100** [comment]
Is it the same if you use the [docker-compose.yml](https://github.com/crazy-max/docker-nextcloud/blob/master/examples/compose/docker-compose.yml) in your examples?
Also I have a self-signed cert for Traefik so I configured it with:
```
[entryPoints.https.tls]
        [[entryPoints.https.tls.certificates]]
         CertFile = "/certs/mycert.crt"
         KeyFile = "/certs/mycert.key"
```
with a specific volume for the Traefik config file:
```
- ./traefik/traefik.toml:/traefik.toml
```
Does it still work?
Thanks
