### ISSUE TITLE
[unRAID] Cron not working

### ISSUE THREAD

**Issue by Deanosim** [crazy-max/docker-nextcloud#20]
### Behaviour
Cron not working
#### Steps to reproduce this issue

1. Create container
2. create cron container

#### Expected behaviour

> It should automatically run cron every 15 minutes

#### Actual behaviour

> The cron container just gives me this error 
`2019-06-28 06:27:16,327 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
crond: USER nginx pid 26 cmd \ php -f /var/www/cron.php
/bin/ash: php: not found`

### Configuration

* Docker version (type `docker --version`) : Docker version 18.06.3-ce, build d7080c1
* Platform (Debian 9, Ubuntu 18.04, ...) : Unraid 6.6.7
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ... I didn't use those, I just ran them manually by typing it into unraid, but it's the same commands as in the readme

### Docker info

```
> Output of command `docker info`
Containers: 48
 Running: 31
 Paused: 0
 Stopped: 17
Images: 44
Server Version: 18.06.3-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.7.3
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: a592beb5bc4c4092b1b1bac971afed27687340c5
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.18.20-unRAID
Operating System: Slackware 14.2 x86_64 (post 14.2 -current)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.72GiB
Name: Home-Server
ID: PU4F:T2WF:MNRF:ILAG:CVMF:4SDX:LFJA:VONS:M5PI:PBCK:HJ4D:L5BH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Logs

```
> Container logs (set LOG_LEVEL to debug if applicable)
Setting timezone to Australia/Sydney...
Setting PHP-FPM configuration...
Setting PHP configuration...
Setting Nginx configuration...
Initializing Nextcloud files / folders...
>>
>> Sidecar cron container detected for Nextcloud
>>
Creating Nextcloud cron task with the following period fields : */1 * * * * \
Fixing permissions...
2019-06-28 06:41:27,694 INFO Included extra file "/etc/supervisord/cron.conf" during parsing
2019-06-28 06:41:27,694 INFO Set uid to user 0 succeeded
2019-06-28 06:41:27,743 INFO RPC interface 'supervisor' initialized
2019-06-28 06:41:27,744 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-06-28 06:41:27,744 INFO supervisord started with pid 1
2019-06-28 06:41:28,746 INFO spawned: 'cron' with pid 25
crond: crond (busybox 1.30.1) started, log level 8
2019-06-28 06:41:29,761 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
crond: USER nginx pid 26 cmd \ php -f /var/www/cron.php
/bin/ash: php: not found
crond: USER nginx pid 27 cmd \ php -f /var/www/cron.php
/bin/ash: php: not found
```

I set it to 1 minute for testing.

**Comment by Deanosim** [comment]
these are the container variables that I use on both if that's helpful
![image](https://user-images.githubusercontent.com/4834976/60299620-7b910800-9970-11e9-902a-7406cf3f4160.png)

**Comment by Deanosim** [comment]
I'm also getting a heck of a lot of these sorts of errors in the logging part of the admin panel, and I can't upload files, So I'd say something went really wrong during install. Any suggestions?
`[PHP] Error: unlink(/data/data/appdata_ocs1fxlhcf4v/css/theming/6a15-2d1e-theming.css.gzip): No such file or directory at /var/www/lib/private/Files/Storage/Local.php#227

at 2019-06-28T07:24:30+10:00`

**Comment by crazy-max** [comment]
Sorry I'm not familiar with unRAID. Maybe you can find help on this [subreddit](https://www.reddit.com/r/unRAID/).
