### ISSUE TITLE
Enabling Social results in an internal server error on access

### ISSUE THREAD

**Issue by Spass1966** [crazy-max/docker-nextcloud#21]
I downloaded and enabled Nextcloud Social. All other services are functional. Accessing https://cloud.hansen.agency/apps/social/ I receive the following error:
```
Internal Server Error

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.
Technical details

    Remote Address: 172.18.0.27
    Request ID: VwXTQqZJubODPDXcKjfZ
```

[nextcloud.log](https://github.com/crazy-max/docker-nextcloud/files/3562859/nextcloud.log)

**Comment by Spass1966** [comment]
Is it best if I redirect this issue to nextcloud/social?

**Comment by crazy-max** [comment]
> Is it best if I redirect this issue to nextcloud/social?

@Spass1966 Yes that looks like an issue with social plugin itself:

`172.18.0.1 - - [31/Aug/2019:22:42:58 +0200] "GET /apps/social/ HTTP/1.1" 500 4916 "https://cloud.hansen.agency/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"`

**Comment by Spass1966** [comment]
Ok will close here and send it over to them. Thanks!

**Comment by crazy-max** [comment]
@Spass1966 You're welcome, keep me in touch.

**Comment by Spass1966** [comment]
New issue is at https://github.com/nextcloud/social/issues/714
