### ISSUE TITLE
cURL timeout / php.ini settings

### ISSUE THREAD

**Issue by EricReiche** [crazy-max/docker-nextcloud#25]
#### Steps to reproduce this issue

1. install fresh nextcloud via docker
2. try to install "Collabora online"

#### Expected behaviour
App gets installed

#### Actual behaviour
Fails with error 
cURL error 28: Operation timed out after 30000 milliseconds with 556618 out of 882318 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

Is it possible to change php.ini settings or increase the cURL timeout?

**Comment by crazy-max** [comment]
Hi @EricReiche, I think this is linked to Collabora Online and not directly to this image. Can you [open an issue on their repository](https://github.com/nextcloud/richdocuments)? Thanks.

**Comment by EricReiche** [comment]
Hi @crazy-max 

no, unfortunetaly not. Collabora was just an example. Installing like half of all apps fails in Nextcloud.

**Comment by crazy-max** [comment]
@EricReiche Looks like an issue with the AppStore: nextcloud/server#17685
