### ISSUE TITLE
sed fails if TZ has a slash "/" in the name

### ISSUE THREAD

**Issue by ajayramaswamy** [crazy-max/docker-nextcloud#31]
in the shell script at rootfs/etc/cont-init.d/03-config.sh on line 68 you have

`sed -e "s/@MEMORY_LIMIT@/$MEMORY_LIMIT/g" -e "s/@TIMEZONE@/$TZ/g" \
  /tpls/etc/php7/conf.d/override.ini > /etc/php7/conf.d/override.ini
`

this fails if I set TZ to "Asia/Kokata"

`
[cont-init.d] 03-config.sh: executing...
Setting timezone to "Asia/Kolkata"...
Setting PHP-FPM configuration...
Setting PHP configuration...
sed: bad option in substitution expression
Setting Nginx configuration...
Initializing Nextcloud files/folders...
Creating automatic configuration...
[cont-init.d] 03-config.sh: exited 0.
[cont-init.d] 04-svc-main.sh: executing... 
`

and the consequence is that the database is not setup so on the first login user creation fails

but if I change TZ=UTC with no slash it works OK

`
[cont-init.d] 03-config.sh: executing... 
Setting timezone to "UTC"...
Setting PHP-FPM configuration...
Setting PHP configuration...
Setting Nginx configuration...
Initializing Nextcloud files/folders...
Creating automatic configuration...
[cont-init.d] 03-config.sh: exited 0.
[cont-init.d] 04-svc-main.sh: executing... 
`

the db is created and I can create the root user too

can you change the sed delimiter from / to #

Thanks

**Comment by crazy-max** [comment]
@ajayramaswamy Thanks for your input. Will be fixed asap.

**Comment by crazy-max** [comment]
@ajayramaswamy Should be ok now.
