### ISSUE TITLE
Several Bugs due to HTTP(S)

### ISSUE THREAD

**Issue by LimitlessGreen** [crazy-max/docker-nextcloud#56]
### Behaviour
I had several issues, since my Nextcloud is running with Docker:
- Federation sharing isn't working
- Some icons can't be loaded: 
 ![No pictures](https://user-images.githubusercontent.com/15064073/103288253-c3b93c80-49e4-11eb-8db4-ba23d5473017.png)

### Reason
It turned out, Nextcloud tries to load some stuff over http and can't reach it.

### Solution
I found the solution here: https://goneuland.de/nextcloud-server-mit-docker-compose-und-traefik-installieren/#6_3_Nextcloud_komplett_auf_HTTPs_umstellen

(I can translate it, if needed)

After this steps are are, federation and icons are working.

**Comment by crazy-max** [comment]
@LimitlessGreen Yes you have to overwrite protocol in your config if you force https: `'overwriteprotocol' => 'https'`.

* https://github.com/crazy-max/docker-nextcloud/issues/19#issuecomment-493661682
* https://github.com/crazy-max/docker-nextcloud/issues/28#issuecomment-567417937

**Comment by LimitlessGreen** [comment]
I took your Traefik example. Maybe you should mention this step there.
