### ISSUE TITLE
Command typo in README

### ISSUE THREAD

**Issue by electrona** [crazy-max/docker-nextcloud#60]
docker-compose exec nextcloud occ   
should be
docker exec -it nextcloud occ

**Comment by crazy-max** [comment]
@electrona That's not a typo. [Compose is the recommended way](https://github.com/crazy-max/docker-nextcloud#docker-compose) to run this image.

**Comment by electrona** [comment]
docker-compose doesn't have an exec option, does it?

**Comment by crazy-max** [comment]
@electrona https://docs.docker.com/compose/reference/exec/

**Comment by electrona** [comment]
My mistake. Although I learned something today.
