### ISSUE TITLE
nextcloud 22 migration

### ISSUE THREAD

**Issue by patzm** [crazy-max/docker-nextcloud#70]
Hi @crazy-max,
do you already have plans to migrate to nextcloud 22? (or 22.1)
Can I help?
best

**Comment by crazy-max** [comment]
Hi @patzm, yeah I've a draft ready. Will be released this weekend.

**Comment by patzm** [comment]
cool, so far the upgrade worked well. Sadly, my existing collectives disappeared. But that is a nextcloud migration issue I guess.
