### ISSUE TITLE
15.0.1 Image not working...

### ISSUE THREAD

**Issue by pageb018** [crazy-max/docker-nextcloud#9]
After updating to the latest container (15.0.1) Nextcloud does not run. When I use the 15.0.0 image everything works fine. Nothing else has changed on my configuration. The docker-compose logs do not show any errors, I am happy to troubleshoot but would need some direction.

**Comment by crazy-max** [comment]
Hi @pageb018, the image has been binded to an unprivileged port `8000` for security reason. See [CHANGELOG.md](CHANGELOG.md) for more info.
